### ISSUE TITLE
Update component processing logic

### ISSUE THREAD

**Issue by danfuterman** [jembi/bsis#263]
I would like to start making use of the `ProductTypeCombination` table and it's associated functionality.
We've previously tried to improve the component processing logic (See #27 and #44), but there wasn't a clear understanding of the requirements at that point, so it missed one or two things.

So, the new plan:

We're currently using the ProductController `/record` endpoint to process components. Here, we specify the source/parent component, and the resulting/processed component (along with the num. units of the component). Rather, we should specify the source component, along with the resulting component combination (i.e. using `ProductTypeCombination`, which in turn uses the mappings in `ProductTypeCombination_ProductType`). This allows us to create multiple component types in a single step. 

So what else do we need?

- Two new fields in `ProductTypeCombination_ProductType` to specify the number of units that can be produced of a certain component - e.g. for paediatric processing, I can make 2 to 6 units (there should also be validation then that these ranges are stuck to).
- The `ProductTypeCombination_ProductType` table specifies what components are produced from a `ProductTypeCombination`, but what seems to be missing is something that maps Component Types to Product Type combinations. i.e. a product type combination should be associated with an initial component type - e.g. see the examples here:
![image](https://cloud.githubusercontent.com/assets/1052668/5753059/f3258860-9c8a-11e4-9e36-b4f1938414d0.png)

This will help in the front-end - when I record new components, the list of possible components to produce should be dependent on my initial component (the component I am processing) - the dropdown list where I select my new component combination should only contain the combinations that are relevant to the initial component.

**Comment by danfuterman** [comment]
@srikanthmalyala - please can you start to work on this today, thanks.

**Comment by srikanthmalyala** [comment]
@danfuterman 

I have few doubts here 

1.  you specified that two new fields are to be added in ProductTypeCombination_ProductType table, I'm assuming the fields are minUnits & maxUnits to produce the number of units.


2. I'm not understanding that why the initial components (Whole blood single pack, whole blood double pack) are  needed ,here can't  directly map pack type to the resulting components.

for example 

single pack -- whole blood
double pack -- PRC-CPDA + FFP
                        PRC-CPDA + FP

**Comment by danfuterman** [comment]
@srikanthmalyala : 

1. Correct -  minUnits and maxUnits

2. Pack Types are specific to donations, but not to component production. When we move to component production, we have to deal with actual components, so it doesn't work to deal with pack types:
![image](https://cloud.githubusercontent.com/assets/1052668/5756748/93165086-9cbb-11e4-984b-f8fbbbc723e7.png)

Also, sometimes there could be two steps to make the final component - e.g I process XX to YY, and then YY to ZZ, so we need to work with components, rather than pack types.

**Comment by srikanthmalyala** [comment]
@danfuterman 

so do we have to create a table for initial components. if we, then what type of relation it has  with the  product type combinations, from the above table it implies one to many relation

**Comment by danfuterman** [comment]
No, any component could be an initial component, all we mean by initial component is that in the component production process, we processed one component into one or more other components - the component we had at the start of the process is the initial component, and the new components are the resulting component(s). As suggested:

```
The ProductTypeCombination_ProductType table specifies what components are produced from a ProductTypeCombination, but what seems to be missing is something that maps Component Types to Product Type combinations. i.e. a product type combination should be associated with an initial component type - e.g. see the examples here: 
```

So what we need is a table that maps ComponentTypes to ProductTypeCombinations.

I will be working on completing this task this evening, I need it completed for the training tomorrow, can you add any commits you've made before you head off, I will work from that, thanks.

**Comment by srikanthmalyala** [comment]
Okay sure , I will be adding max and min units into the system,

**Comment by srikanthmalyala** [comment]
Note : ProductTypeCombination_ProductType is a auto populated table when creating product combination. Yet there is no interface to update min and max units

**Comment by danfuterman** [comment]
:+1:
