### ISSUE TITLE
Align backing forms and view models

### ISSUE THREAD

**Issue by srikanthmalyala** [jembi/bsis#268]

**Comment by srikanthmalyala** [comment]
https://docs.google.com/a/jembi.org/spreadsheets/d/1ZlZFFbfKm7MhtCItAjP8099CX6uzOcUjaO4XmfrFtXw/edit#gid=0

**Comment by srikanthmalyala** [comment]
@danfuterman 

The response of blood test is 
  
      {
          "bloodTest": {
          "validResults": [
             "+",
              "-"
            ],
         "testName": "Anti-A",
         "testNameShort": "Anti-A",
         "isActive": true,
         "negativeResults": "-",
         "rankInCategory": 1,
         "positiveResults": "+",
         "category": "BLOODTYPING",
         "id": 1
        }

In the above response the validResults is of type List but the backing form expects it to be String , 

I have a question that the backing form validResults property type should  changed to List and then convert to string or the input from Ui itself is of string type 
      }

**Comment by danfuterman** [comment]
:+1:
