### ISSUE TITLE
Add some unit tests for the repositories

### ISSUE THREAD

**Issue by timler** [jembi/bsis#318]
Add some unit tests for the repositories - these will be useful for testing the new refactoring branches.

**Comment by timler** [comment]
I've made a first stab at this, but unfortunately it was not as easy as I thought. I got quite a few unit tests for the repositories running in Eclipse, but they failed when running in sequence via Maven.

The reason for this was two fold:
 1. The previous architecture of the DBUnit tests was not closing the connections to the database after doing inserts and deletes. This caused the number of connections in the pool to run out after I'd added a number of tests and then the tests started to hang. I added the obligatory "connection.close" and refactored the existing tests to fix this problem.
 2. The automagical Spring rollback is not happening when inserting or updating data in the unit tests. This is causing the "DELETE_ALL" to fail - by hanging once again - in certain tests. I've had this problem before in previous projects and it is usually caused by the spring setup (applicationContextTest.xml). Unfortunately I didn't manage to solve this problem, so had to sadly add "@Ignore" for these tests.

Following on from point 2 (rollback not working & DBUnits DELETE_ALL hanging) - I tried quite a few things today and none of them worked. I explicitly set the rollback to true (it should be that anyway). I forced the connection to "autorollback". I suspect we need to simply the application context for tests - I am not sure we'd need a CP30 pool for examples.

Another thing I tried was to just remove DELETE_ALL. This, in theory, can be replaced by using "CLEAN_INSERT". Unfortunately this only gave temporary relief. The next problem was that the test data was getting mixed up as CLEAN_INSERT only drops the tables mentioned in the specific tests dataset. If the tests used different tables, then the data tables not referenced by the second test would remain. It could be possible to run some kind of "clean" dataset that just contains empty tables, but I unfortunately did not get this working. DBUnit is strict wrt to ordering of the tables and I got stuck on foreign key references.

So, I think much more work will be required for this to be a full solution. We can test the read-only repository functions though.

**Comment by danfuterman** [comment]
@timler - Thanks for the thorough feedback and work on this - I'm going to create a PR for the branch to make it simpler to view the changes, and I will also merge the latest master branch in that includes all your refactoring work.

**Comment by timler** [comment]
I managed to fix the issues with the unit tests. There were actually two issues and not exactly what I expected.

1. There was an issue with the dataset being deleted and the inserted/updated data still being present. The problem wasn't with the Spring setup like I suspected, but was with the `@After` annotation executing before the transaction was rolled back. I switched all the DBUnit test cases to use `@AfterTransaction` instead and this solved the problem where DBUnit was hanging during clean up.

2. The second problem was that one test was not rolling back and this was causing other tests to run into foreign key issues when they tried to drop some tables but not others. This was caused by one test (DonorRepositoryTest) not running in a transaction. To solve this I just added the `@Transactional` annotation to the entire test. You can do it for each test method, but it's easier to put it on the class level and all tests will be included in a transaction.

**Comment by danfuterman** [comment]
Great news, great solution. Thanks @timler

**Comment by timler** [comment]
OK, so this is my status after complete a fair chunk of the Repository DBUnit tests

Repository Tests not done
 - LabSetupRepository
 - TipsRepository
 - WorksheetRepository
 - WorksheetTypeRepository
 - CompatibilityTestRepository
 - RequestRepository
 - RequestTypeRepository

Incomplete Tests:
 - ProductRepository:
  - `findMatchingProductsForRequest`
  - `findNumberOfIssuedProducts`
  - `addProductCombination`

Existing Tests (not checked for coverage):
 - DonorCommunicationsRepository
 - DonorRepository

Issues discovered:
 - BloodTestingRuleEngine: `ttiUninterpretable` is always set to false
 - DonationRepository: `findAnyDonationMatching` has a bug in the HSQL
 - DonationRepository: `findDonations` has a bug in the HSQL when querying a DIN with parameter name `panelIds`/`donorPanelIds`
 - ProductRepository: `isProductCreated` has a bug in the HSQL with property `donationIdentificationNumber`
 - ProductRepository: `getAllUnissuedProducts()` has a bug in the HSQL with the property `isIssued`
 - ProductRepository: `getAllUnissuedProducts(String, String, String)` has a bug in the HSQL with `model.product.Product`
 - ProductRepository: `getAllUnissuedThirtyFiveDayProducts` (both of them) have bugs in the HSQL with `model.product.Product`
 - ProductRepository: `getAllProducts(String)` has a bug in the HSQL with `model.product.Product`
 - ProductRepository: `findProduct(String)` has a bug in the HSQL with property `productNumber`
 - ProductRepository: `findProductTypeByProductTypeName(String)` has a bug in the HSQL with property `productType`
 - ProductRepository: `deleteAllProducts` is a hard delete and won't work if there are foreign key references to any Product (e.g. ProductStatusChange)
 - ProductStatusChangeReasonRepository: `getAllProductStatusChangeReasonsAsMap` will only return one `ProductStatusChangeReason` per `ProductStatusChangeReasonCategory` (there are many)
 - ProductTypeRepository: `getProductTypeByName(String)` has a bug in the HSQL with property `productType`
 - TestBatchRepository: `deleteTestBatch` sets `isDeleted` to false
 - UsageRepository: `findProductUsage`, `findUsageByProductNumber(String)`, `deleteUsage(String)` and `findAnyUsageMatching(String, String, String, Map)` have errors in the HSQL with `productNumber`

Possibly issues:
 - DonationRepository: `verifyDonationIdentificationNumber` throws an NoResultException when it tries to return a null instead.
 - Circular dependency of repository and controller packages with UtilController being used to retrieve the logged in Spring user.
 - ProductRepository: `splitProduct` has a parameter named `numProductsAfterSplitting` but there will always be +1 products
 - ProductTypeRepository: `getAllParentProductTypes` actually returns the `pediProductType` and also fails with a NPE if the `ProductType` with id=1 does not have a `pediproducttype_id` defined
 - ProductTypeRepository: `getProductTypeByIdList` is an unclear method
 - RoleRepository: `deleteRole` will fail with foreign key references if the associated `Users` and `Permissions` are not removed first
 - TestBatch: method `isIsDeleted` could cause issues because it does not conform to standards
 - FormField: possible duplication of `DonorForm` `callingName`

**Comment by timler** [comment]
Please note that the "productNumber" issues in ComponentRepository and UsageRepository have been fixed in 1c1dc25 - during the refactor of Product to Component.

There is now a new issue for `UsageRepository`: See test `testFindAnyUsageMatching` which throws an HSQL error: `dateUsed of: model.usage.ComponentUsage [SELECT u FROM model.usage.ComponentUsage u WHERE (u.component.componentIdentificationNumber = :componentIdentificationNumber OR u.useIndication IN (:useIndications)) AND (u.dateUsed BETWEEN :dateUsedFrom AND :dateUsedTo) AND (u.isDeleted= :isDeleted)]`
