### ISSUE TITLE
Test Batch Release

### ISSUE THREAD

**Issue by danfuterman** [jembi/bsis#373]
The test batch workflow requires an additional step before the batch is closed, where the batch is reviewed, validated and released. The review and validation is done by the double entry of test outcomes, and reviewing test outcome discrepancies - tti tests that require confirmatory testing, blood group serology test outcomes that are ambiguous, or require a confirmatory outcome (i.e. for first time donors). The double entry of test outcomes (validation) will be taken care of in a separate task, and the review is partly managed by the implementation of https://github.com/jembi/bsis-frontend/issues/209. This task is mainly focused on test batch release:

 - a test batch can only be released if there are no outstanding test outcomes for the initial set of required tests (i.e. the standard set of tti and blood group serology tests). 
 - When a batch is released, all samples that don't have any discrepancies are released, and the associated logic is run on the associated donors and components. Currently this logic occurs when the batch is closed, and this needs to be moved to the batch release stage. The samples that still have discrepancies are not released yet. The initial batch release is a bulk release, following that each sample is released as it's discrepancy is resolved. Once all discrepancies have been resolved, the batch can be closed. Essentially, any logic that is currently linked to the closing of a batch should be moved to the release stage.
 - The batch can only be released by users with the testing supervisor role

**Comment by bausmeier** [comment]
@jonojhs test

**Comment by danfuterman** [comment]
:+1:
