### ISSUE TITLE
Remove unused general config properties

### ISSUE THREAD

**Issue by danfuterman** [jembi/bsis#384]
The following configurations aren't used in the system:
 - donation.bpSystolicMax	Blood Pressure systolic value cannot be more than 250	integer	250
 - donation.bpDiastolicMax	Blood Pressure diastolic value cannot be less than 0	integer	150

These should be removed using a liquibase changeset.

**Comment by debonair** [comment]
@danfuterman  these are used here https://github.com/jembi/bsis-frontend/blob/master/app/scripts/controllers/donors.js#L254 and here

https://github.com/jembi/bsis-frontend/blob/master/app/scripts/controllers/donors.js#L1223

**Comment by danfuterman** [comment]
@debonair - Can you double check that again, the system should be making use of `donation.donor.bpSystolicMax` and `donation.donor.bpDiastolicMax` - not to be confused with the two that should be removed - `donation.bpSystolicMax` and `donation.bpDiastolicMax` - i.e. the ones in use have an extra `.donor` in their name.

**Comment by debonair** [comment]
@danfuterman you are right.

**Comment by debonair** [comment]
@danfuterman please review

**Comment by jonojhs** [comment]
@debonair let me know when I can test :)

**Comment by debonair** [comment]
@jonojhs am not sure how you could test this, because all it does is remove a couple of configs for the GeneralConfig table, I think this is something @bausmeier or @danfuterman can test

**Comment by jonojhs** [comment]
@debonair Ok sure, my understanding is that it would be removed from view in the General Configurations under settings.

**Comment by debonair** [comment]
@jonojhs yes, once I deploy the branch
