### ISSUE TITLE
Update Recent Donation Batches View and Search

### ISSUE THREAD

**Issue by danfuterman** [jembi/bsis#404]
Currrently, the Recent Donation Batches view shows a list of recently closed batches, but this should be updated to include the following:

- Search by Venue
- Search by Batch date (created date)

For an example of this, refer to the Post Donation Counselling form:

![image](https://cloud.githubusercontent.com/assets/1052668/10933038/420c9844-82de-11e5-84c3-0dcdf5f4d73b.png)

The difference here is that the page should be preloaded with the following values:
 - Venue - Any Venue
 - Batch date - the past 7 days

The user can then change these values in the form to update the results shown in the table.

**Comment by debonair** [comment]
@danfuterman should this endpoint also return deleted batches?

**Comment by debonair** [comment]
@danfuterman actually it seems it is not possible to delete a batch anyway from the front end

**Comment by danfuterman** [comment]
Please see #379 (PR #398) with regards to your Q - changes have been added there to allow for deletion of donation batches. I'd suggest reviewing this and evaluating if it would be worthwhile branching off of that PR for this task.

**Comment by debonair** [comment]
@danfuterman I see, then back to my actual question, should I include deleted ones when I fetch recent batches? or should I have a flag that says includeDeleted?

**Comment by danfuterman** [comment]
There is no requirement in this task to display deleted batches (i.e. a `closed` batch is not the same as a `deleted` batch, so there is no need in this task to include deleted batches in the list of batches.
