### ISSUE TITLE
Edit Donation - Pack Type Issue (Critical)

### ISSUE THREAD

**Issue by danfuterman** [jembi/bsis#418]
Currently, it is possible to edit the Pack Type of a donation, however, there are no rules on the kind of Pack Types that can be selected. For ineligible donors, where the donation batch is not historical, the Pack Types should be limited to those that do not produce components

Example use case - I added a `Test Only` donation for an ineligible (Do Not Bleed) donor, but when editing the donation I changed this to a `Triple Pack`.

This was never accounted for in the initial set of rules to edit donations, but is a critical issue since it allows for 'bad' donations. The rules should be extended to account for this.

**Comment by danfuterman** [comment]
@jonojhs please see new issue.

**Comment by jonojhs** [comment]
@danfuterman have created issue -  https://jembiprojects.jira.com/browse/BSIS-261
(I just copied your explanation)
